"""update config gemini

Revision ID: cf1f59fbceb0
Revises: 9a4cb985e40a
Create Date: 2025-04-07 14:37:14.738163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1f59fbceb0'
down_revision: Union[str, None] = '9a4cb985e40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gemini', sa.Column('last_expired_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gemini', 'last_expired_at')
    # ### end Alembic commands ###
